---
- name: Clone the Aerospike repository
  git:
    repo: https://github.com/aerospike/aerospike-client-php
    dest: /tmp/aerospike-ext
    accept_hostkey: yes
    depth: 1

- name: Create libcrypto.so symlink
  file:
    src: /usr/lib/x86_64-linux-gnu/libcrypto.so
    dest: /usr/local/lib/libcrypto.so
    owner: root
    group: root
    state: link

- name: Create libcrypto.a symlink
  file:
    src: /usr/lib/x86_64-linux-gnu/libcrypto.a
    dest: /usr/local/lib/libcrypto.a
    owner: root
    group: root
    state: link

- name: Install Aerospike client
  shell: |
    DOWNLOAD_PHP_UNIT=0 ./build.sh --loglevel OFF
    make -s install
  args:
    chdir: /tmp/aerospike-ext/src/aerospike
    creates: /usr/lib/php/20160303/aerospike.so

- name: Create aerospike.ini
  template:
    src: /tmp/ansible/templates/aerospike.ini.j2
    dest: "{{ php_conf_path }}/mods-available/aerospike.ini"
    owner: root
    group: root
    mode: 0644

- name: Enable Aerospike extension
  command: phpenmod aerospike
