---
- name: Self-signing a CSR for a wildcard domain
  lineinfile:
    dest: "/etc/ssl/openssl.cnf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^#.?(copy_extensions.?=.+)$'
      line: "copy_extensions = copy"

- name: Add timezone support to MySQL
  shell: |
    mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --user=root --password=secret mysql
