---
- name: Make vagrant home directory tree readable by vagrant user
  file:
    path: /home/vagrant
    state: directory
    mode:  "u=rwx,g=rx,o=rx"
    owner: vagrant
    group: vagrant
    recurse: yes

- name: Add vagrant user to groups
  user:
    name: vagrant
    uid: 1000
    state: present
    groups: www-data,adm,cdrom,dip,plugdev,lxd,lpadmin,sambashare
    append: yes

- name: Allow passwordless sudo to vagrant
  lineinfile:
    dest: "/etc/sudoers"
    line: "%sudo ALL=(ALL,ALL) NOPASSWD{{':'}} ALL"
    state: present

- name: Add Composer global bin to PATH
  lineinfile:
    path: /home/vagrant/.profile
    line: "PATH=/home/vagrant/.composer/vendor/bin:$PATH"
