---
  php_use_managed_ini: true
  php_install_recommends: no
  php_enable_php_fpm: true
  php_fpm_pool_user: "vagrant"
  php_fpm_pool_group: "vagrant"
  php_webserver_daemon: nginx
  php_packages_state: "latest"
  php_session_save_path: "/tmp"
  php_memory_limit: "512M"
  php_error_reporting: "E_ALL"
  php_display_errors: "On"
  php_date_timezone: "UTC"
  php_post_max_size: "100M"
  php_upload_max_filesize: "100M"

  php_enable_apc: true
  php_apc_enable_cli: "1"

  php_opcache_enable: "1"
  php_opcache_enable_cli: "1"
  php_opcache_revalidate_freq: "0"

  php_version: "7.1"
  php_mysql_package: "php{{ php_version }}-mysql"
  php_conf_path: "/etc/php/{{ php_version }}"

  php_apache2_conf_path: "{{ php_conf_path }}/apache2"
  php_cli_conf_path: "{{ php_conf_path }}/cli"
  php_fpm_conf_path: "{{ php_conf_path }}/fpm"
  php_phpdbg_conf_path: "{{ php_conf_path }}/phpdbg"

  php_fpm_pool_conf_path: "{{ php_fpm_conf_path }}/pool.d/www.conf"
  php_fpm_daemon: "php{{ php_version }}-fpm"
  php_fpm_listen: "/var/run/php/{{ php_fpm_daemon }}.sock"

  php_extension_conf_paths:
    - "{{ php_apache2_conf_path }}/conf.d"
    - "{{ php_cli_conf_path }}/conf.d"
    - "{{ php_fpm_conf_path }}/conf.d"
    - "{{ php_phpdbg_conf_path }}/conf.d"

  php_conf_paths:
    - "{{ php_apache2_conf_path }}"
    - "{{ php_cli_conf_path }}"
    - "{{ php_fpm_conf_path }}"
    - "{{ php_phpdbg_conf_path }}"

  php_packages:
    - build-essential
    - imagemagick
    - libpcre3
    - libpcre3-dev
    - php-apcu
    - php-apcu-bc
    - php-gearman
    - php-igbinary
    - php-imagick
    - php-libsodium
    - php-memcache
    - php-memcached
    - php-mongodb
    - php-msgpack
    - php-pear
    - php-phalcon
    - php-redis
    - php-ssh2
    - php-xdebug
    - php-yaml
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-bz2"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-common"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-dba"
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-gmp"
    - "php{{ php_version }}-imap"
    - "php{{ php_version }}-intl"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-ldap"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-mcrypt"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-odbc"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-pgsql"
    - "php{{ php_version }}-phpdbg"
    - "php{{ php_version }}-pspell"
    - "php{{ php_version }}-readline"
    - "php{{ php_version }}-recode"
    - "php{{ php_version }}-soap"
    - "php{{ php_version }}-sqlite3"
    - "php{{ php_version }}-tidy"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-xmlrpc"
    - "php{{ php_version }}-xsl"
    - "php{{ php_version }}-zip"
