---
  php_version: "7.1"
  php_use_managed_ini: true
  php_install_recommends: no
  php_enable_php_fpm: true
  php_fpm_pool_user: "vagrant"
  php_fpm_pool_group: "vagrant"
  php_webserver_daemon: nginx
  php_packages_state: "latest"
  php_session_save_path: "/tmp"
  php_memory_limit: "512M"
  php_error_reporting: "E_ALL"
  php_display_errors: "On"
  php_date_timezone: "UTC"
  php_post_max_size: "100M"
  php_upload_max_filesize: "100M"
  php_enable_apc: true
  php_apc_enable_cli: "1"
  php_opcache_enable: "1"
  php_opcache_enable_cli: "1"
  php_opcache_revalidate_freq: "0"
  php_mysql_package: php7.1-mysql
  php_fpm_conf_path: "/etc/php/7.1/fpm"
  php_fpm_daemon: php7.1-fpm
  php_extension_conf_paths:
    - /etc/php/7.1/fpm/conf.d
    - /etc/php/7.1/apache2/conf.d
    - /etc/php/7.1/cli/conf.d
  php_conf_paths:
    - /etc/php/7.1/fpm
    - /etc/php/7.1/apache2
    - /etc/php/7.1/cli
  php_conf_path: /etc/php/7.1
  php_packages:
    - build-essential
    - imagemagick
    - libpcre3
    - libpcre3-dev
    - php-apcu
    - php-apcu-bc
    - php-gearman
    - php-igbinary
    - php-imagick
    - php-libsodium
    - php-memcache
    - php-memcached
    - php-mongodb
    - php-msgpack
    - php-pear
    - php-phalcon
    - php-redis
    - php-ssh2
    - php-xdebug
    - php-yaml
    - php7.1-bcmath
    - php7.1-bz2
    - php7.1-cli
    - php7.1-common
    - php7.1-curl
    - php7.1-dba
    - php7.1-dev
    - php7.1-fpm
    - php7.1-gd
    - php7.1-gmp
    - php7.1-imap
    - php7.1-intl
    - php7.1-json
    - php7.1-ldap
    - php7.1-mbstring
    - php7.1-mcrypt
    - php7.1-mysql
    - php7.1-odbc
    - php7.1-opcache
    - php7.1-pgsql
    - php7.1-phpdbg
    - php7.1-pspell
    - php7.1-readline
    - php7.1-recode
    - php7.1-soap
    - php7.1-sqlite3
    - php7.1-tidy
    - php7.1-xml
    - php7.1-xmlrpc
    - php7.1-xsl
    - php7.1-zip
