---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - /tmp/ansible/vars/all.yml
    - /tmp/ansible/vars/geerlingguy-nginx.yml
    - /tmp/ansible/vars/geerlingguy-php.yml
    - /tmp/ansible/vars/geerlingguy-composer.yml
    - /tmp/ansible/vars/geerlingguy-redis.yml
    - /tmp/ansible/vars/geerlingguy-mysql.yml
    - /tmp/ansible/vars/geerlingguy-nodejs.yml
    - /tmp/ansible/vars/geerlingguy-postgresql.yml
    - /tmp/ansible/vars/geerlingguy-php-pecl.yml
    - /tmp/ansible/vars/goreplace.yml
    - /tmp/ansible/vars/zephir.yml

  roles:
    - locale
    - geerlingguy.nfs
    - geerlingguy.packer-debian
    - packages
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.git
    - geerlingguy.composer
    - geerlingguy.blackfire
    - geerlingguy.memcached
    - geerlingguy.redis
    - geerlingguy.mysql
    - geerlingguy.daemonize
    - geerlingguy.mailhog
    - geerlingguy.nodejs
    - geerlingguy.postgresql
    - geerlingguy.php-pecl
    - zephir-parser
    - phalcon.zephir
    - f500.beanstalkd
    - phalcon.ngrok
    - youbond.supervisor
    - goreplace
    - config
    - mongodb
    - aerospike
    - handlersocketi
    - weakref
    - pinba
    - php-libs
    - php
    - cleanup
