---
- name: Final upgrading of the system
  command: "{{ item }}"
  with_items:
    - apt -y update
    - apt -y upgrade

- name: Clean up apt
  command: "{{ item }}"
  with_items:
    - apt -y clean
    - apt -y autoremove
    - apt -y autoclean

- name: Make vagrant home directory tree readable by vagrant user
  file:
    path: /home/vagrant
    state: directory
    mode:  "u=rwx,g=rx,o=rx"
    owner: vagrant
    group: vagrant
    recurse: yes
